services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "${DB_HOST_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  go-service:
    build: .
    restart: on-failure:5
    ports:
      - "${GO_SERVICE_PORT}:8080"
    env_file: .env
    volumes:
      - ./configs:/app/configs
      - ./migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy
